spring:
  rabbitmq:
    username: admin
    password: admin
    addresses: 192.168.0.32
    # 应答机制 生产者发送消息到交换机，成功或失败进行回调通知 配置 默认none
    publisher-confirm-type: correlated
    # 回退机制 交换机发送信息到队列如果失败，将消息返还给生产者配置，默认false
    publisher-returns: true
